### ISSUE TITLE
Volume isn't bounded when using hotkeys

### ISSUE THREAD

**Issue by GeQi** [lhc70000/iina#1004]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Steps to reproduce:**
When using `⌘ +` or `⌘ -` to adjust volume, the value could go beyond 100 and 0. I do however think allowing volume to go beyond 100 by his mean could potentially be helpful, but down below zero surely should not be intended.

**Comment by kettch** [comment]
It is indeed quite helpful, and I think it would be helpful as well to make that available using the mouse wheel (but stopping at 300 or 400). Otherwise, I find I often need to have the computer master volume at near maximum to have a decent movie volume, and it makes other sounds that may occur really loud in comparison.

**Comment by lhc70000** [comment]
Fixed/added in 0.0.13.

**Comment by kettch** [comment]
Just downloaded version 0.0.13, and the lower bound is indeed in place. However, the mouse wheel to change volume still is stopped at 100.

**Comment by lhc70000** [comment]
@kettch The max volume is also set to 100 by default. Please configure it in Preferences > Codec.

**Comment by kettch** [comment]
Oh neat, thanks @ lhc70000 !
