### ISSUE TITLE
Thumbnail cache is not invalidated if the contents of a movie change

### ISSUE THREAD

**Issue by mistydemeo** [lhc70000/iina#1058]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.12 build 37

**Expected behavior:**

If the contents of a video change, I expect the scrollbar thumbnails to change as well.

**Actual behavior:**

If thumbnails have previously been generated for a video at a specific path, any future videos with the identical path will have the same thumbnail cache until the cache is manually cleared.

**Steps to reproduce:**

1. Create a video at a specific path, such as `~/Desktop/test.mov`.
2. Delete that video.
3. Copy a new video with different contents into this path.
4. Hover over the scrollbar, and see that the thumbnails are from the video from step 1.

**Comment by saagarjha** [comment]
@lhc70000 How long would it take to compute a checksum of a video file?

**Comment by mistydemeo** [comment]
How about calculating a checksum of a region of a file? Say, the first 512KB?

**Comment by saagarjha** [comment]
I'm not sure if this approach would always work, especially if the video format is something along the lines of "file header+video data". If we changed the end of the video (modifying it after 512 KB) it would still require invalidating the thumbnail cache.

**Comment by braineo** [comment]
For quick check can test against modified date, video length, file size along with file name.

**Comment by euf** [comment]
I believe that the easiest way is to store video file’s path and it’s hash (e.g md5 or something faster). 
Every time video is opened its hash should be recalculated (in the background, not to interrupt playback) — only if the hash doesn’t match previously stored one for old video file, the thumbnails cache cache should be regenerated. 
P.S. This makes sense only if computing hash is really fast, at least faster than generating thumbnails every time.
P.P.S. Maybe storing only hashes is even more efficient than storing file paths, since regenerating thumbnails every time when a movie was moved to another location is not good.
P.P.P.S. Time for old jokes: “_There are only two hard things in Computer Science: cache invalidation and naming things_”.

**Comment by inflation** [comment]
Theoretically, we can compute the checksum pretty fast on whole file if we don't want any cryptographic feature, for instance, using `xxhash` for 13.8 GB/s on a 64-bit machine. But it will throttle on I/O speed in such case. 

I'm thinking using several metric to compare two files:
1. File size: changing the video content will normally change the file size.
2. Modified Date: not very accurate, but has some point.
3. Random sample chunk's checksums: final measurement, can prevent most collisions. 

We could check each level until failure. I think this approach can prevent most coincidences.

**Comment by lhc70000** [comment]
Fixed in 0.0.14.1.

**Comment by lhc70000** [comment]
Sorry, wrong issue.

**Comment by inflation** [comment]
Fixed in  b0aa0a8.
