### ISSUE TITLE
The keybinding of Play (F8) will shadow system's keybinding

### ISSUE THREAD

**Issue by hanfeisun** [lhc70000/iina#1085]
When IINA is opened, even run in background, it will intercept many useful system-level keybindings, which brings some issues.

For example, F8 is used as Play/Pause key in iTunes. But if IINA is run in background, I cannot use F8 to control the play and pause of iTunes anymore. I tried to remove the Play/Pause keybinding in IINA's Preferences, but it doesn't help at all.

**System and IINA version:**

- macOS 10.13
- IINA 0.0.12

**Expected behavior:**

When I disable the Play/Pausing keybinding in IINA, the system-level play/pausing keybinding will still work for iTunes.

**Actual behavior:**

When I disable the Play/Pausing keybinding in IINA, the system-level play/pausing keybinding still doesn't work for iTunes. It seems that the keyboard event is intercepted by IINA and never send to the OSX system.

**How often does this happen?**
Everytime.

**Comment by saagarjha** [comment]
This is a feature, not a bug. You'll notice that other apps such as QuickTime and Safari (playing videos) do this as well, since they use the new MediaPlayer framework that has this behavior.

**Comment by hanfeisun** [comment]
I just tried QuickTime. I opened both QuickTime and iTunes, then I found pressing F8 on my MBP can still control iTunes without any problem.

However, as soon as I opened IINA, F8 doesn't work anymore. This doesn't look a feature to me.

**Comment by saagarjha** [comment]
This behavior binds the media keys to the last application you've interacted with using the media keys. To see how it works, you'll need to perform these steps in *exactly* this order:

1. Play something in iTunes.
2. Open QuickTime.
3. Press play.
4. Move focus away from QuickTime to some other application.

At this point you should see that QuickTime will respond to your play/pause key rather than QuickTime. If you'd like to check what your keys control, there's a new widget for Notification Center called "Now Playing" that will reflect what you're currently playing.

If you really want IINA to ignore key events, you'll need to:

1. Open IINA and hit play.
2. Open iTunes and hit play.

Since iTunes is the second application you've interacted with, you should be able to control it instead.

**Comment by hanfeisun** [comment]
@saagarjha Thanks so much for your detailed explanation! The trick of "moving focus away" works for quicktime well. 

However, the second experiment doesn't work for me. 

Here is what I did: I open IINA and hit play by mouse, then open iTunes and hit play by mouse. Now I press the F8 button. What I expect to control is iTunes, but it turns out that the IINA is controlled. 

Is this reproducible on your machine?

**Comment by saagarjha** [comment]
D'oh! It looks like I'm running a debug build of IINA that contains the changes from #1063, which I thought had been already merged. We'll work on getting it integrated so that these changes can land by 0.0.13 if all goes well.

**Comment by hanfeisun** [comment]
I see, thanks for the help! Glad this feature will be in the newer version :-)
