### ISSUE TITLE
Window doesn't close after video ends.

### ISSUE THREAD

**Issue by ttepasse** [lhc70000/iina#1091]
**System and IINA version:**

- macOS 10.13 (with the supplemental update of this week)
- IINA 0.0.12

**Expected behavior:**

I have the setting *"Keep window open after playback finishes"* **not enabled**. As such I expect that the (fullscreen) window closes when the video is done.

**Actual behavior:**

It doesn't. Repeatable.

This is not the bug of the lost settings ( #1049 ). I had that same bug some times and then the re-set default settings are displayed in the Preferences window, e.g. my custom keybindings are not displayed anymore, etc.

For this bug it the setting *"Keep window open after playback finishes"* doesn't seem to have any effect. Checking it, quitting IINA, restarting, unchecking it ... doesn't help.

**Comment by kxxc** [comment]
same here

[https://github.com/lhc70000/iina/issues/1056](https://github.com/lhc70000/iina/issues/1056)

**Comment by lhc70000** [comment]
- You must have "Play next item automatically" turned on.
- You must have "Add files in the same folder automatically" disabled, or the current media is the last item in your playlist. Otherwise, it will continue to play the next item.
- If still not work, try disabling "Keep window open after playback finishes" and enabling it again.

**Comment by ttepasse** [comment]
Tested in 0.0.14 and it works. Thanks for your response!
