### ISSUE TITLE
(questions) Pre render 4k videos? (downscaling)

### ISSUE THREAD

**Issue by irrelevantspechack** [lhc70000/iina#1223]
Hello I downloaded iina originally to try to play 4K-10bit video on my macbook pro retina 13" (2560x1600). The job was good (impossible to read on VLC) but there was still a delay between audio and image and some ghosting. I guess this is due to the on-the-go rendering and downscaling? (the fans were at full power and the mac very hot).

Is there a way to pre-render the video, in order to view without theses ghosting/audio&video not sync? 
Do watching one time the video and then coming back to the beginning will use some already made calculous or does it will re-downscale & render on-the-go?

Also, i tried to see a .mkv H264 1920x1080 movie with iina and vlc, i did not noticed a slight difference for now, but i saw that in vlc settings, video output is on "predefined", and the only other option is "display 1 1280x800". (1280x800 is my desktop resolution) Do you know if VLC know I can show more pixels and do it? (taking advantage of the retina display)

Last of the last, I sometime tried (in the past, without the use of iina) to download uncompressed blu-ray and play them on my so 2560x1600 13" retina macbook, and I always noticed a problem with a grainy image. For some reasons some high definition videos works with VLC (only players i knew) and some others not. I guess it's a converting format matter. 

In order to save time, will iina will make a better work for reading blu-ray than VLC (and avoid this grainy effect)? Or it will do the same?

Thanks

**Comment by inflation** [comment]
If you want to downscaling your video before watching it, please try to use `ffmpeg` or other GUI tools like Handbrake to transcode your video to appropriate size. The video player itself only decode the video.

**Comment by irrelevantspechack** [comment]
if the video player only decodes the video how it can still read real 4K video on a 2K monitor?

Maybe it's a function of the graphic card of the computer to then downscaling to 2K (or choosing which pixel to show, which is the same thing). 

There is an option "use physical resolution for retina display". This mean it understand and do something with the resolution.

**Comment by inflation** [comment]
Yes. The player would decode compressed content into raw frame data, and then render it on the screen to what resolution the window is. Your problem is in decoding part. From the description, I assume it can only use software decoding for 10-bit videos.  If you didn’t touch any advanced downscaling algorithm settings for mpv, then the time on it won’t affect performance.

**Comment by atomicsaiko** [comment]
@irrelevantspechack Which year is your MacBook Pro 13" released?

1. If your UHD/4K video is encoded with HEVC codec and with 10 bit depth, then there is no mobile CPU that will playback this at realtime speed with software decoding. However, If you have the 2017 MBP with Kaby Lake Intel CPU, then with High Sierra and IINA you can offload the decoding of the HEVC bitstream to the build-in hardware decoder in the CPU which as is very good at this task only. 

My Macbook Pro 13" (2017) plays UHD HEVC video (8 / 10 bit) just fine with no stutter, because of hardware decoding. If I force IINA to use software decoding then CPU rockets to 100% and playback is jerky. 

2. Pre-render, in your case would simply mean transcoding to a lower resolution and computationally less intensive video codec, like AVC. You can do this in `ffmpeg`. Feel free to ask me for a suitable set of custom params to start transcoding. 

3. I don't know what a grainy image looks to you, but movies can look a little grainy to simulate a film like visual. These days most of that grain artificially added. Blu-ray is not uncompressed. It is AVC encoded at a higher rate to retain more detail. Most of the 'download movies' are re-transcodes at a lower rate using the gold-standard x264 encoder.

4. Some players don't have the logic embedded to deal with display scaling. I don't use VLC, but IINA at least uses 'physical pixels' which is the correct way to display video. Else it would be upscaled. Display scaling is fine for vector image and text which can be rendered nicely. 

5. The case of player X plays this and player Y not can't be easily answered. That is a multitude of variables like...

- Operating System
- IGP or video card present with embedded hardware decoder
- Media file structure, like container, video/audio codec and supporting metadata
- Hardware acceleration API's like DXVA, VAAPI, VDA etc. (OS and driver dependent)

6. If media file that is being played back has higher coded resolution than the actual display monitor, the player simply does downsizing. This can be software (Lanczos, Bicubic etc.) or even done by the hardware decoder further down the pipeline as well. This may actually help performance a little since less pixels have to be shown on your display monitor.

**Comment by irrelevantspechack** [comment]
Thanks you very much for detailed answer. I have early 2015 mbp retina, so i guess it don't have hardware decoding? 

So if i have to use ffmeg, i guess i have to to make all the re encoding out of a video player and so thats not what i was looking for. I was actually looking for a feature that would do the transcoding before playing the video in order to have good fps and no shutter, that will put it in the memory and delete it when quitting.. (or something like that). 


About the grainy effect actually I don't have this effect when I download an already transcoded / scaled resolution. It happen just if I download the full blu-ray without any conversion made (like the one with VIDEO_TS files). Basically downloading good transcoded blu-ray that weight like between 10 and 18gb give me a better image than downloading the full 40GB+ blu-ray and playing it on my macbook pro.

I know there is this "added grain" to look more cinema, but on same titles I checked and it's not the same at all for the two versions.


Can I have good results downsampling / downscaling UHD bluray with proper software? Like downscaling them to exactly match retina display resolution, and maybe with a (low but better at the end) better interpolation process or something like that. On some movies I really love I would take that time if it can give me better image at the end that the already very good work of transcoding team that show a result at 1080p.

**Comment by atomicsaiko** [comment]
1. Your MacBook Pro from 2015 does have hardware decoding for established codecs like H.264/AVC and MPEG-2, but not HEVC.

2. In your case, realtime playback of UHD HEVC encoded video is not possible. You have to transcode this to a lower resolution first manually. Your transcoding speed is already limited to the rate of decoding UHD HEVC, and on top of that re-encoding the decoded stream to another codec.

3. Grain effect is subjective. In case of re-transcoded, if bitrate is low enough the grain is simply destroyed by the higher quantizers in the encoder. Or if resolution is scaled down, depending on the resizing algorithm used the grain particles comes closer or get destroyed partially as well. A combination of the above mentioned two scenarios doubles the effect. It appears that your eyes like a clean 'sterile' image.

4. You can have proper results with re-transcoding if you know what you are doing. 

But I guess we will have to end the conversation here as your original post does not really describe a problem that is related to IINA. The conlusion is that your MBP (2015) does not have the processing capacity to playback UHD HEVC video at the minimal required coded framerate, despite best efforts from IINA to decode as efficienty as possible. 

After all this repository here is about IINA and we are going a bit off topic here.

**Comment by irrelevantspechack** [comment]
Ok yes you are right. 

> You can do this in ffmpeg. Feel free to ask me for a suitable set of custom params to start transcoding.

You said that so I wanted to bounce on that. Any platforms we can talk about that?

**Comment by atomicsaiko** [comment]
Please encode your email address with http://ctrlq.org/encode/ and paste the generated code here. This is to prevent spambots scraping your email address. I will contact you about using `ffmpeg`.

**Comment by irrelevantspechack** [comment]
Hello,

I finally gave up on transcoding this file.
I noticed ffmeg doesn't really work on my mac os 10.13.2 (high sierra).

I have a question, because i found other useful software for converting
video, if I have real UHD content (3840*2160p if i don't mistake), at what
resolution i want to convert it to enjoy the maximum of my 2560 by 1600 13"
retina display? Then, i can find that in photoshop scale option i guess (to
see what match the most), anyway, any advice for others mac compatible
software that can underscale 4K video for my retina display?

thanks

2017-11-20 13:27 GMT+01:00 atomicsaiko <notifications@github.com>:

**Comment by saagarjha** [comment]
Of course, the gold standard for such conversions would be FFmpeg–I'm sure they'd like to hear why it's not working on your computer.

**Comment by irrelevantspechack** [comment]
im sorry this message was meant to be an email i don't know why it appeared here

**Comment by atomicsaiko** [comment]
@irrelevantspechack Please resume the conversation via email.

FFmpeg certainly works on Mac, Linux and Windows. Most other freeware 'one-click-converters' are just GUI abstractions from FFmpeg. Or you could purchase enterprise transcoding software from the likes of Telestream, Harmonic, Sorenson, ATEME, Imagine Communications etc.
