### ISSUE TITLE
Remeber window size (don't size window to video resolution)

### ISSUE THREAD

**Issue by phizi** [lhc70000/iina#124]
Hi!

I really like the first preview of your player!
Here's a request: remember the window dimensions when opening another video.
Whenever I open a video with V0.0.1 (from finder using "open with") the UI is sized to the native video dimensions.

I would love to see an option which keeps the current window dimensions when the next video is opened (like vlc does: there's an option within the interface settings which says "Scale interface size to current video size" (I'm using the German version of VLC so I don't know the exact English translation here). If you don't check this option, any new video is scaled to the actual window size.

Many thanks in advance,
Phi

**Comment by lhc70000** [comment]
It's a good suggestion. Currently IINA doesn't resize window only when opening media from playlist. We'll consider adding this option as soon as possible.

**Comment by fredwu** [comment]
On a related note, the "Resize to video size only when opening files manually" applies correctly (i.e. does NOT resize) when you manually click a video from the playlist. But if the current video finishes and it automatically switches to the next video, then the window DOES resize, which is not the expected behaviour.

Hope that makes sense. :P
