### ISSUE TITLE
IINA is not good for Chinese support

### ISSUE THREAD

**Issue by liweihao5253** [lhc70000/iina#1418]
System and IINA version:

- macOS 10.13.2
- IINA 0.0.15

With some Chinese fonts, the Arabic numerals and letters in the text look weird.
The size is different.
![2018-01-25 11 53 07](https://user-images.githubusercontent.com/35565160/35370433-c4434716-01c8-11e8-9a3e-0dcc7c62ef7e.png)

**Comment by inflation** [comment]
I think it’s because your font doesn’t have the characters so the player choose them from the default font. Then they may be rendered differently even having the same configuration. Also, some Chinese fonts don’t have calibrated Latin characters (e.g. grabbing from another font), so they may looked weird too. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
