### ISSUE TITLE
Oversaturated HEVC 10bit - all the time

### ISSUE THREAD

**Issue by jnpatrick99** [lhc70000/iina#1424]
Whenever I play HEVC 10bit videos they look oversaturated and overbrightened. It's definitely problem of the IINA because for example same videos on VLC look perfect (but they play very slowly). All other videos, pictures etc look perfect on my monitor. IINA plays mp4 H264 and other video perfectly. The only problem is combination of IINA and 10bit HEVC.

Is it something that can be tuned in the preferences somewhere? I tried disabling hardware decoding it doesn't make a difference!

- macOS 10.12.6
- IINA 0.0.15

**Comment by inflation** [comment]
How about 10-bit H264 files?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bodayw** [comment]
What color space the HEVC 10-bit files you have problem with are using? Maybe provide a MediaInfo of one of those files?

**Comment by jnpatrick99** [comment]
Sure! Here's MediaInfo for one of the files:

```
Video
ID                                       : 10
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2 h 32 min
Bit rate                                 : 30.7 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.155
Stream size                              : 32.7 GiB (92%)
Writing library                          : x265 2.1+69-c97c64ab8b8e:[Windows][GCC 6.2.0][64 bit] 10bit
Encoding settings                        : cpuid=1173503 / frame-threads=3 / numa-pools=8 / wpp / no-pmode / no-pme / no-psnr / no-ssim / log-level=2 / input-csp=1 / input-res=3840x2160 / interlace=0 / total-frames=218951 / level-idc=51 / high-tier=1 / uhd-bd=0 / ref=2 / no-allow-non-conformance / repeat-headers / annexb / no-aud / no-hrd / info / hash=0 / no-temporal-layers / open-gop / min-keyint=23 / keyint=250 / bframes=4 / b-adapt=0 / b-pyramid / bframe-bias=0 / rc-lookahead=15 / lookahead-slices=8 / scenecut=40 / no-intra-refresh / ctu=64 / min-cu-size=8 / no-rect / no-amp / max-tu-size=32 / tu-inter-depth=1 / tu-intra-depth=1 / limit-tu=0 / rdoq-level=0 / signhide / no-tskip / nr-intra=0 / nr-inter=0 / no-constrained-intra / strong-intra-smoothing / max-merge=2 / limit-refs=3 / no-limit-modes / me=1 / subme=1 / merange=57 / temporal-mvp / weightp / no-weightb / no-analyze-src-pics / deblock=0:0 / sao / no-sao-non-deblock / rd=2 / early-skip / rskip / fast-intra / no-tskip-fast / no-cu-lossless / no-b-intra / rdpenalty=0 / psy-rd=2.00 / psy-rdoq=0.00 / no-rd-refine / analysis-mode=0 / no-lossless / cbqpoffs=0 / crqpoffs=0 / rc=crf / crf=13.0 / qcomp=0.60 / qpstep=4 / stats-write=0 / stats-read=0 / vbv-maxrate=160000 / vbv-bufsize=160000 / vbv-init=0.9 / crf-max=0.0 / crf-min=0.0 / ipratio=1.40 / pbratio=1.30 / aq-mode=1 / aq-strength=1.00 / cutree / zone-count=0 / no-strict-cbr / qg-size=32 / no-rc-grain / qpmax=69 / qpmin=0 / sar=0 / overscan=0 / videoformat=5 / range=0 / colorprim=9 / transfer=16 / colormatrix=9 / chromaloc=0 / display-window=0 / master-display=G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50) / max-cll=1002,225 / min-luma=0 / max-luma=1023 / log2-max-poc-lsb=8 / vui-timing-info / vui-hrd-info / slices=1 / opt-qp-pps / opt-ref-list-length-pps / no-multi-pass-opt-rps / scenecut-bias=0.05
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0050 cd/m2, max: 4000 cd/m2
Maximum Content Light Level              : 1002 cd/m2
Maximum Frame-Average Light Level        : 225 cd/m2

```

**Comment by bodayw** [comment]
So the MediaInfo indicate the file is in BT.2020 color space, which is what causing the problem here. It has nothing to do with HEVC or 10-bit.

But what confused me is that if you have a monitor with a much narrower color gamut than BT.2020 (almost for sure) and are not using color management on IINA (not enabled by default), the result would appear desaturated, rather than oversaturated.

Are you using any color management features on IINA, like ``--icc-profile`` or ``target-prim``?

**Comment by jnpatrick99** [comment]
Thank you of for the analysis and the suggestions. The main monitor is LG 27UD69P that supports 10 bit and my Mac System Info displays "Pixel Depth: 30-Bit Color (ARGB2101010)" which is 10 bit as well. I also have second 8-bit monitor connected and it looks even more oversaturated on it. Both monitors are color-profiled and LG is using factory color profiling provided by the manufacturer. For example Photoshop and Lightroom display everything perfectly, web pages look like they should. VLC displays everything like normal. And IINA seems to be displaying all other files perfectly.

The only problem is when I use IINA to play HEVC 10-bit files with the profile like the one above. I have around 10 files like that and they all share the same problem.

I tried both switches you provided and seems `--target-prim` desaturated everything a little bit. It's getting better. But it's still oversaturated and the bright spots still look overbrightened.

**Comment by bodayw** [comment]
The color depth of the monitor panel and the color depth in which video is encoded are two different things. It is irrelevant whether your monitor is 10-bit or 8-bit here.

By default IINA does not perform any kind of color management, unlike most applications on the Mac (which use Apple's ColorSync) or some other applications like Photoshop (which by default perform color management on its own). If you have never been using ``--icc-profile`` or ``--target-prim`` before, you were seeing "wrong" colors all the time. It might be pretty close to correct, given that your main monitor has a close to exact 100% sRGB color gamut, which is the same color gamut used by almost any non-UHD video files. But now you are playing file with a different color gamut of BT.2020, which is much wider than sRGB, so the color will appear much desaturated.

Not sure how you tried the two mpv options (they're not "switches" and they won't do anything without given a value), but to enable color management in IINA, you will need to go to Preferences - Advanced, add an entry in ``Additional MPV options``, with the Name being ``icc-profile`` and Value being the path to the icc color profile of your monitor, could be something like ``~/Library/ColorSync/Profiles/xxxxx.icc``. Or you can also get pretty close to correct result by adding an entry of ``target-prim`` as Name and ``bt.709`` as Value (BT.709 has the same color primaries definition as in sRGB, which is the closest value to your monitor).

**Comment by bodayw** [comment]
Oh, I just thought that HDR might be the reason why you saw "oversaturated" instead of desaturated color. The MediaInfo you pasted above indicates it's also an HDR video, and IINA (mpv) does HDR to SDR conversion by default, such that HDR videos can still be watchable on an SDR screen (but of course not as good as on a screen that meets HDR standards and has native HDR support, and there is no defined correct way to convert HDR to SDR).

Playing an HDR video on an SDR screen without conversion would cause the video look very dim.

I don't know how VLC deals with UHD HDR videos, but they could perform some kind of color gamut and/or HDR to SDR conversion by default.

In principle, to get correct result (or say close to correct results since you don't have an HDR screen) with IINA on your setup, you should color profile your monitor and add the ``icc-profile`` option as I said above. Try this and see what you get.

**Comment by jnpatrick99** [comment]
Awesome! Thank you for the help! I was trying to put these switches into `iina-cli`'s command line. Obviously that didn't work.

Putting `icc-profile` into advanced settings did the trick! `target-prim` also helped but `icc-profile` looks better. IINA is awesome, seriously the best video player in the world! Keep it up guys!

**Comment by inflation** [comment]
I’m just wondering why `ice-profile-auto` is not in the default setting. We should add it to prevent further confusion like this. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bodayw** [comment]
@jnpatrick99 Glad to hear it worked for you.

@inflation ``icc-profile-auto`` does not work in IINA due to some kind of limitations of the mpv client API. Right now we can only enable color management by using ``icc-profile=/path/to/profile.icc`` (and of course it won't work well for setups with multiple screens).

While set ``icc-profile-auto`` by default in mpv might not make much sense (as most people use their monitors not profiled and many cheap laptop screens have non-standard color gamut), I agree that it should be the default behavior in IINA, as all Mac models produced in the past few years have pretty close to standard color gamuts (sRGB or DCI-P3 D65) and has correspondent profiles built in, and also 4K HDR files with BT.2020 color gamut are becoming popular now. Even on a not profiled screen using a generic icc profile, it's still better to assume it as sRGB and convert the color (on average it will still be closer to correct since BT.2020 is way much wider than sRGB).

Maybe IINA can detect the icc profile of the current display IINA is using in the system settings by itself, and pass that to mpv with ``--icc-profile``.

**Comment by inflation** [comment]
@bodayw Yeah, you are right. `icc-profile-auto` does not work in external OpenGL context rendering. We may need to "reinvent the wheel" like how mpv handles this: https://github.com/mpv-player/mpv/issues/594

**Comment by kirbyzhou** [comment]
1.0.0-Beta1 still have problem.
The highlight part of picture has a problem of color gradation fracture.

IINA 1.0.0-beta1
![4k-hdr-iina-1](https://user-images.githubusercontent.com/3401630/38786154-b54a5270-4158-11e8-83bc-4b3d7b55f5c3.jpg)
![4k-hdr-iina-2](https://user-images.githubusercontent.com/3401630/38786158-b8baded4-4158-11e8-91f1-961604a0837a.jpg)

MPV 0.28.2 seems better
![mpv-1](https://user-images.githubusercontent.com/3401630/38786161-bcda2c04-4158-11e8-98f2-2c3cb24f559c.jpg)
![mpv-2](https://user-images.githubusercontent.com/3401630/38786163-bf7b24fe-4158-11e8-80b1-cf2af4576c42.jpg)

VLC 3.0.1 the best
![vlc-1](https://user-images.githubusercontent.com/3401630/38786165-c48954a2-4158-11e8-889c-b117f928d339.jpg)
![vlc-2](https://user-images.githubusercontent.com/3401630/38786170-cab37010-4158-11e8-8e2e-6460d1608c56.jpg)



BDRip.REMUX and H.265 comes with the same problem.

VLC play the same video with no problem.

Here is the sample video:

http://demo-uhd3d.com/files/uhd4k/Sony_4K_HDR_Camp.mp4  [Download by Xunlei]
or 
ed2k://|file|Sony_4K_HDR_Camp.mp4|1204810814|34e179d04b765ff13a4d8894f7e29b58|h=hwb3sunxdinaxkel4tzis3wqf4dzuxhk|/

**Comment by kirbyzhou** [comment]
May I simply replace the MPV within IINA to latest version?

**Comment by bodayw** [comment]
Might be related to mpv-player/mpv#4976

**Comment by kirbyzhou** [comment]
So, any suggestion for us users?

**Comment by bodayw** [comment]
@kirbyzhou See my latest comment in #1673.

**Comment by ValZapod** [comment]
BTW, the sample I found is not even HDR. After some further search I did find what is PQ. https://andytather.net/Panda/Files/Video/HDR/Sony_4K_HDR_Camp.mp4
