### ISSUE TITLE
DCP Playback Support 数字电影包播放支持

### ISSUE THREAD

**Issue by lydasia** [lhc70000/iina#1498]
It will be nice if you could add DCP(Digital Cinema Package) playback support, thank you!

希望可以增加播放数字电影包的能力，非常感谢！

**Comment by saagarjha** [comment]
IINA uses mpv internally for playing videos, and this is something they'd need to add support for. Normally, I'd ask you to file a bug upstream, but it looks like they're already on it: https://github.com/mpv-player/mpv/issues/2337

**Comment by lydasia** [comment]
@saagarjha @inflation 

Thanks for your attention. Actually both mpv and iina do play mxf files in DCPs. But a DCP is not just a video, it's a collection of files, including audio, image and some data. So it needs some extra support.

感谢你们的注意。实际上现阶段mpv和iina均可以正常播放DCP中的mxf文件。但是DCP包并不是一个视频文件，它是一个文件的集合，包括音轨，图像序列，和一系列描述文件。所以它需要一些额外的支持。

![mpv](https://user-images.githubusercontent.com/22676960/36360787-4bf49676-1527-11e8-8d3c-03d3f993da42.png)
![iina](https://user-images.githubusercontent.com/22676960/36360788-4c0e6060-1527-11e8-90c6-0c3141eb7974.png)

https://en.wikipedia.org/wiki/Digital_Cinema_Package

https://www.douban.com/note/283170348/

**Comment by atomicsaiko** [comment]
@saagarjha Actually that MPV issue ticket actually leads back to a FFmpeg ticket, since they are using their libraries for the splitting and decoding of media files. From my research, that is not high on their list to make proper DCP playback possible. And I wouldn't be hopefull about it coming anytime soon.

DCP playback is not a use case that you will see often as it is a very proprietary format for use in Digital Cinema's. The creation and playback of such media is naturally associated with enterprise media creation software that is expensive. 

My opinion would be that DCP is only created to make things needlessly complicated to cater to the proprietary nature of the industry. FFmpeg is technically able to decode the files as they are just MXF Op-atom containers containing single essence only. JPEG2000 (video) and PCM (audio). The main issue is simply parsing the XML files and metadata to build a decoding chain in the player so it knows which Op-atom MXF files to take and synchronise both video and audio.

I am not sure about your exact use case for DCP playback. But if it is purely for the sake of playback and non production purpose, you might as well gather all the video and audio essence and transcode + multiplex it into a single container. But even that conversion can be tricky with the XYZ colorspace it is coded in, as I presume you will be watching the content on a standard sRGB monitor. Colorspace conversions aren't as simple as it seems. 

All in all, for the average user that just wants to watch content. I wouldn't bother with DCP at all. It is made for Digital Cinema usage and not for commodity playback like opening any regular MP4 file.
