### ISSUE TITLE
iina-cli doesn't support network url

### ISSUE THREAD

**Issue by anonymous5l** [lhc70000/iina#1683]
i look up iina-cli source code find looks like doesn't support network url i finally hope it's can be support. or it's has other solution?

**Comment by inflation** [comment]
The CLI doesn’t handle the URL. It passes everything directly to the player. So it supports anything the player supported. Network streams is surely one of them. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by PengJieXu** [comment]
i use iina-cli to open url then got exception "错误 无法打开文件或流" but if i open IINA app and use `打开 URL` to open "rtmp://" url is fine

**Comment by inflation** [comment]
It's probably better that you indicate you want to open RTMP streams in the issue, instead of vague "network url". 

As for the problem, I found that the regex we are using to check url only accept http(s) and ftp protocol. I think we should accept all URLs no matter what protocol it using. @lhc70000

**Comment by PengJieXu** [comment]
it couldn't be better thx

**Comment by lhc70000** [comment]
@inflation Would you like to push a fix?
