### ISSUE TITLE
iina-cli opens unfocused instance of the player

### ISSUE THREAD

**Issue by robertgzr** [lhc70000/iina#1710]
**System and IINA version:**

- macOS 10.11.6
- IINA 1.0.0-beta1-build71

**Expected behavior:**

With IINA closed, when I open a video with the cli `iina-cli /path/to/video` I should get an instance of the player in the foreground playing that file.

**Actual behavior:**

IINA opens in the background and starts playing.

**Notes:**

If this is the intended behavior can there be a flag to force IINA to open in the foreground?
I can pass `--mpv-ontop` but that still gives me no control over the instance.

**Comment by inflation** [comment]
I can’t reproduce the issue. It would always open a new instance to play the file. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by corwin-of-amber** [comment]
I would like to comment on the topic since the OP seems to have phased out. Running the cli does open a new instance of IINA, but the player window does not take to the foreground and appears below the terminal window (the last window that had the focus).

Setting `--mpv-ontop` does bring it forward, but then it stays on top and prevents the user from switching to other apps. There should be an option to make the video instance take focus as it's opened, the same way it does when double-clicking a file in Finder.

**Comment by MuntashirAkon** [comment]
I find it quite annoying that IINA should open in the background instead of the foreground.
Currently, as a workaround I'm doing this in my script:
```sh
osascript<<EOF
tell application \"System Events\"
    set processList to every process whose unix id is $app_pid
    repeat with proc in processList
        set the frontmost of proc to true
    end repeat
end tell
EOF
```
Where `$app_pid` is the process id of IINA, again which can be get by adding one to the process id of `iina-cli` (It is extremely unlikely that an executable will run in the middle of the two processes).

**Comment by MuntashirAkon** [comment]
Just a thought: while this feature could be very useful in some cases, quite the opposite is true for other cases. For instance, I may want to use the `--pip` option to open a media file directly in the PiP mode, in which case, I don't want to be distracted by the IINA player window. I think this feature should be disabled in this case, or there should be an argument to disable it manually.

**Comment by MuntashirAkon** [comment]
At this point, #2014 could be the right solution.

**Comment by alejx** [comment]
We are working on a fix to improve the main window during pip mode. Stay tuned.

**Comment by lhc70000** [comment]
@saagarjha #350 and #380.
