### ISSUE TITLE
Need to restart the app to get the online subtitles search working

### ISSUE THREAD

**Issue by aroomthedoomed** [lhc70000/iina#1785]
- macOS 10.13.5
- IINA 1 beta2 build 80

When I'm watching a list of media, and when subtitles are available at OpenSubtitles.org, I can download the subtitle for the first media played. If IINA was freshly started.

But when the next media will play, and I'm trying to get the sub online, I can't get anything and nothing is displayed, no network error. I need to close and re-open the app and then I can fetch the sub.

**Comment by inflation** [comment]
Can you provide any logs when searching failed?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aroomthedoomed** [comment]
there you go:

https://pastebin.com/zzFATL6T

IINA found a sub for the episode 4 (did found and download the wrong sub though - ep 5) and then after the change next track, I re-try to look for sub and nothing happened.

**Comment by HarukaMa** [comment]
@aroomthedoomed

**Comment by mrelwood** [comment]
It's been over a year since this issue was "fixed", but for me the exact same issue still remains on the latest 1.0.4.

Running Iina 1.0.4 with beta updates enabled, on MacOS 10.14.6.

**Comment by crnkovic** [comment]
It's been a long time, but this issue still exists. v1.1.2, macOS Big Sur.

**Comment by engineerbaraazakariya** [comment]
it is almost a year since last comment and still in 1.2.0 macos we still have same issue it always need to close and reopen to solve this, the issue is annoying because I will need to close all instances of IINA this will lead me to lose the progress time of every instance of IINA.
![Screen Shot 2022-02-16 at 5 36 18 PM](https://user-images.githubusercontent.com/5383782/154286978-4e9695e7-889a-4c6e-8efb-06aba2f90e85.png)

**Comment by kokuken85** [comment]
never fixed? i have that problem now 

OS 13.5. IINA 1.3.5

**Comment by engineerbaraazakariya** [comment]
Switched to Windows+MPC-HC and things are awesome since then, there is no good Media player for Mac. (no games too).
