### ISSUE TITLE
Equalizer completely broken on since beta 2 and beta 3

### ISSUE THREAD

**Issue by GHubbler** [lhc70000/iina#1867]
It seems that the equalizer is completely broken since 1.0.0 beta 2 and 1.0.0 beta 3. 
Sliders don't change the sound. Loading presets from beta 1 throws mediocre errors. Moving sliders and trying to save a new presets leaves me with blank text input fields. if I enter anything similar to the old eq-preset it throws - again - weird errors. Btw. the new settings are similar horrible as VLC. Old style hat some kind of mac-feeling and was very uncluttered and neat. New one is just the opposite.
I'm reverting back to beta 1 build 71. It was near to perfect. 
I hope you get the project back on the track because I am really worried about the development in beta 2 and 3.

**Comment by lhc70000** [comment]
> Sliders don't change the sound.

It's because mpv has deprecated its own equalizer filter. It should have been replaced by a FFmpeg one, but I completely forgot this before. I'll fix it in the next version. BTW, please open an issue as soon as possible once you found a bug, and feel free to poke me :)

> Moving sliders and trying to save a new presets leaves me with blank text input fields.

> Old style hat some kind of mac-feeling and was very uncluttered and neat. New one is just the opposite.

What "new setting" are you referring to? I can't remember any other equalizer related settings other than the one in audio sidebar…… Where are the "presets" and "blank text input fields"? Do you mean the audio filter window?

**Comment by ErikMinekus** [comment]
I think he means he doesn't like the Preferences redesign.

**Comment by lhc70000** [comment]
@ErikMinekus Thanks, I see. 

@GHubbler 

However it's becoming more and more hard to embed such a bunch of controls and labels in a traditional preference window. Lots of users got lost in those settings, let alone there're multiple localization problem related to that layout. The uncluttered and neat layout you see may become nightmare when displayed in another language. Therefore I tried to do some redesign on the window itself rather than the layout of controls and labels (yes, the layout didn't change too much) and also added a search box. BTW VLC is using the traditional "Mac-like" preference window and I if I had to say, it's more similar to the previous pref window of IINA.

I still want to know what "presets" do you mean. If you believe it's a bug, please open another issue and explain it in detail.

**Comment by GHubbler** [comment]
Many thank for caring. Yes, I think the old Preferences were way more usable and nicer. I can imagine it is a challenge to put in a a lot of control settings but am also worried that this dialog itself becomes a bit out of control ;)
Personally I like a simple preferences and the Mac-like styling was it, what makes Iina shine in this aspect.

To your questions:
Preferences is no bug, just an opinion of myself. Sorry, it belongs not this bug and mixed different topics together. 

Thanks for the feedback to the equalizer. It is one of my most used features so I really miss this thing. I would be glad to see this back in one of the upcoming version.

Thanks again, Iina is acutally one of the best players out there. I like it very much.

**Comment by stefan1983** [comment]
Any info yet when beta 4 will be dropped (with fixed Equalizer)!?

Thanks

**Comment by lhc70000** [comment]
Hopefully in one week.
