### ISSUE TITLE
Hiding progress bar manually

### ISSUE THREAD

**Issue by sunqingyao** [lhc70000/iina#195]
Could you please implement a button so that users can hide the progress bar by hand?

While it is true that the progress bar would hide automatically when the cursor isn't in the player window, currently it's awkward to hide the progress bar when in full screen mode.

**Comment by lhc70000** [comment]
You can set auto hiding duration (currently 5s) to a smaller value in `Preference->UI->On Screen Controller`.

It's a known bug (#141) that OSC does not not hide automatically when entering fullscreen. As a workaround, you may move the mouse cursor a little bit after entering fullscreen. It should be fixed in next release.

**Comment by sunqingyao** [comment]
Yeah, most video players don't have this feature, but I personally think it's a nice feature to have as a fallback. Also, impatient people would definitely love that.

Waiting for several seconds is OK, except when the progress bar happens to cover the subtitle, and characters in the video are not talking in your mother tongue.

**Comment by lhc70000** [comment]
How about adding an option "Auto hide OSC when entered fullscreen"?

**Comment by sunqingyao** [comment]
"Auto hide OSC when entered fullscreen" would also be a good idea 👍

**Comment by lhc70000** [comment]
Close due to fixed in [0.0.3](https://github.com/lhc70000/iina/releases/tag/v0.0.3) (Added "click to hide OSD" option).
