### ISSUE TITLE
Bug of PiP on IINA 1.0 beta

### ISSUE THREAD

**Issue by rukkora** [lhc70000/iina#2068]
(I'm not good at English. Sorry for my poor English.)

- macOS 10.14
- IINA 1.0.0 beta4 build 90

Shortcut key for "Toggle Picture-in-Picture" doesn't work.
I can enable Picture-in-Picture, but I cannot disable by pressing the shortcut key.

**Comment by saagarjha** [comment]
The PIP bug you reported should have already been fixed by 658c11ba4e9491d8a2c1759b55c794a87bb3be6b; I don't think it made it into any of the builds yet but it should ship as part of 1.0. I'm going to close this for now, but if you don't see this resolved in the next build feel free to reopen this and yell at me to take a look at it again.

**Comment by rukkora** [comment]
Thank you very much.
