### ISSUE TITLE
Issue in change_lib_dependencies.rb

### ISSUE THREAD

**Issue by HarukaMa** [lhc70000/iina#208]
Current rewrote version of `change_lib_dependencies.rb` assumes mpv is installed through homebrew. If mpv is self-compiled, the script will simply wipe out the `libmpv/lib` folder without doing anything more.

@xu-cheng please review.

**Comment by xu-cheng** [comment]
Since the document states to install mpv from Homebrew first, I don't think this is a bug. So the question is whether to support mpv from other sources than Homebrew. Personally, I don't think this is necessary, considering it is tool used only by developer. 

At the same time it is not too hard to support such feature, all you need to do is changing this line https://github.com/lhc70000/iina/blob/master/other/change_lib_dependencies.rb#L57
