### ISSUE TITLE
Change Cmd+0 shortcut to Cmd+` | 调节窗口大小的快捷键建议去掉 Cmd+0

### ISSUE THREAD

**Issue by xshwy** [lhc70000/iina#26]
建议修改成command + ` / 1 / 2 类似这样的，如果用command+0，需要两个手才能切换，不太方便。

**Comment by zhuangqh** [comment]
在键盘的右边也有一个command键呢，cmd+0可用右手单手操作：）

**Comment by lhc70000** [comment]
如果很多用户有同样想法，会修改。待调查。

**Comment by JiamingSuen** [comment]
+1 for this enhancement, right hand is more often on a mouse when using an iMac other than a MacBook.
Probably the better way is to resize the window automatically when the video resolution is too small(like MPlayerX does).
BTW it would be really nice if IINA can use the same shortcut as MPlayerX since most user of IINA is originally from MPlayerX. Thanks!

**Comment by saagarjha** [comment]
-1 for this change. ⌘-` is already a macOS standard shortcut for switching between windows. Just because IINA doesn't have multiple windows right now doesn't mean it won't have any later (#79, #209, #187); this will break user expectations when these changes are added.

**Comment by lhc70000** [comment]
I think @saagarjha has made it very clear so the shortcut will remain current one.

@JiamingSuen IINA is based on mpv and has no relationship with MplayerX, and there's no evidence for "most IINA user come from MplayerX". I'll try to make shortcuts logical and general, but will not try to imitate the scheme of any other product, sorry for that.
