### ISSUE TITLE
Improvement on osc and title bar behavior

### ISSUE THREAD

**Issue by alejx** [lhc70000/iina#273]
According to QuickTime Player, when the mouse stopped above the osc or the title bar, they will not disappear until the mouse leave. 
A relate issue is that currently double clicking title bar when it is on the screen is make IINA goes into full screen, however it should be minimize. If we make the title bar behaves as that in QuickTime, that will make more sense.

**Comment by lhc70000** [comment]
> According to QuickTime Player, when the mouse stopped above the osc or the title bar, they will not disappear until the mouse leave.

Then OSC just doesn't disappear automatically?

> currently double clicking title bar when it is on the screen is make IINA goes into full screen

Current titlebar is a fake one, so it's actually double clicking the window; however we can make it minimize / zoom easily.

**Comment by alejx** [comment]
> Then OSC just doesn't disappear automatically?
Yes. You can have a try.

> Current titlebar is a fake one, so it's actually double clicking the window; however we can make it minimize / zoom easily.
Why cannot we make it a real one? Is there any restrictions?

**Comment by lhc70000** [comment]
> Yes. You can have a try.

Users just need to set hiding time to a long enough value if they need such behavior. We need to give them more choices.

> Why cannot we make it a real one? Is there any restrictions?

Now it's just a legacy of some resultless try in early development; but actually we can do more since it's a plain NSView:

- Draw something else other than title text, like a status bar
- Change the appearance (like material) easily
- Control hiding duration and animation

**Comment by alejx** [comment]
> Users just need to set hiding time to a long enough value if they need such behavior. We need to give them more choices.

Sometimes users need to watch the title bar and OSC more than usual time. e.g. They may want to see the file which is currently playing for a longer time, then they can stop the mouse on the title bar to make title bar does not disappear. Same idea to OSC.

**Comment by megadr01d** [comment]
> Sometimes users need to watch the title bar and OSC more than usual time. e.g. They may want to see the file which is currently playing for a longer time, then they can stop the mouse on the title bar to make title bar does not disappear. Same idea to OSC.

I would make this an option (hovering Title Bar and OSC overrides hiding duration) since the default hiding behavior (whether they are hovered or not) is highly desirable for people who watch movies from a distance.

I can't count the number of times my pointer was not triggering any control elements, pressed Full Screen on the remote or keyboard to start playing, jumped to bed under careful arranged blankets and the increased window size would make the pointer hover the OSC, making it permanently visible.

It's not fun throwing socks at the trackpad waiting for the pointer to get the hell out of the way.

**Comment by megadr01d** [comment]
I kinda take back what I said. Now I realize the OSC automatically hides even when I'm continually clicking on a button (rewind, for instance) so I guess @alejx is right. The default video player behavior of not hiding the OSC when it's being hovered, makes sense.

**Comment by alejx** [comment]
See 56e31ab.
