### ISSUE TITLE
Version newer than 0.0.1 hangs when playing video.

### ISSUE THREAD

**Issue by joppuyo** [lhc70000/iina#288]
Version 0.0.1 works beautifully, but if I try to use version 0.0.2 or 0.0.3 IINA hangs and stops responding when trying to open a video file. Also, I noticed that for some reason the icon in the dock changes to mpv icon when this happens.

![](http://i.imgur.com/r2i5Ack.png)

Macbook Pro 15" (Late 2016, Touch Bar)

[Log file](https://www.dropbox.com/s/9vglfxe4lpkxvg0/iina.log?dl=0)

For the time being, I'm reverting back to version 0.0.1.

**Comment by lhc70000** [comment]
Sorry for inconvenience.

I've received several similar reports, and seems that it only happens when you enabled custom mpv config directory (in Preference > Advanced) and have some special configurations in it.

The reason why it works for you in 0.0.1 is that **in 0.0.1 has a bug that doesn't load config dir containing `~`**, i.e. custom config directory is actually not loaded. If you're fine with 0.0.1, you can just switch to the latest version and **disable custom mpv config directory** as a workaround.

I'm still not sure why it happens, perhaps it's a mpv problem or your config file is in wrong format. Would you mind sending me the contents of your mpv config directory?

**Comment by joppuyo** [comment]
Thanks for the quick reply, it seems like this it was the "Use config directory" setting that caused the hanging. I disabled it and now IINA is working fine.

If it's any use, my mpv configs are the following:

```
vo=opengl
interpolation
scale=ewa_lanczossharp
video-sync=display-resample

```
