### ISSUE TITLE
Crash when play some .mkv files

### ISSUE THREAD

**Issue by SayoMelu** [lhc70000/iina#343]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.4

**Steps to reproduce:**
[magnet:?xt=urn:btih:DA5142099DA45138EBBAB05A40664C98AC2C0496](magnet:?xt=urn:btih:DA5142099DA45138EBBAB05A40664C98AC2C0496)
Download a .mkv file in this magnet link, and open it with IINA
**How often does this happen?**
Every times

**Comment by SayoMelu** [comment]
[Uploading [CASO&amp;SumiSora][Puella_Magi_Madoka_Magica][BDRIP][GB_BIG5].torrent.zip…]()
Or this torrent

**Comment by lhc70000** [comment]
It may be a general bug and not related to some files.

If it just quit without any alert, please try this version:

Google Drive: https://drive.google.com/open?id=0B7tEU25gz8nhTGFwNGxNZUJlemc
Baidu: 链接: https://pan.baidu.com/s/1i4U3Ttz 密码: s24j

Otherwise, please upload the crash report generate by system.
