### ISSUE TITLE
Reduce file name when the title bar is not long enough.

### ISSUE THREAD

**Issue by alejx** [lhc70000/iina#353]
**System and IINA version:**

- macOS 10.12.4 developer beta 2
- IINA Latest develop branch build 9

**Expected behavior:**

![screen shot 2017-02-09 at 6 14 23 pm](https://cloud.githubusercontent.com/assets/20237141/22808818/9900e524-eef3-11e6-9bd8-be28c1a1938b.png)
P.S. This capture is from 0.0.4 build 7.

**Actual behavior:**

![screen shot 2017-02-09 at 6 14 52 pm](https://cloud.githubusercontent.com/assets/20237141/22808825/aacee38c-eef3-11e6-9164-a5c120fb95ab.png)

**Steps to reproduce:**

Use build 9. Play a file with relative long file name and resize the window to the smallest size. The file name overlaps window controllers (sorry I don't know how to call those three points).

**How often does this happen?**

This does not happen in 0.0.4 build 7. But happens every time in latest build 9.

**Comment by lhc70000** [comment]
@saagarjha Why did you change the constraints for title bar?

**Comment by saagarjha** [comment]
@lhc70000 It's a remanent from a commit I removed from #165, which had support for a Document Icon Button. I've added the support back in #366. As a side note: please let me know when you revert a commit. For a small graphical bug like this, that doesn't cause a crash or make the application unusable, with a very simple fix, is probably not a good reason to revert a commit with other things in it.

**Comment by lhc70000** [comment]
@saagarjha 

I noticed that you also

- removed some height constraints. It doesn't cause error, but having height constraints will make it easier to add more controls in later development.
- used aspect constraints. Is there any special reason for doing this? I mean, they are just simple buttons so it perhaps didn't simplify a lot, and having height+width constraints is more flexible, since we may not require them to be square in other layouts (in the future).

I was not sure whether these changes breaks other UI, so I reverted it first.

I missed them when checking #165, sorry for that. But seems that you didn't mention it in the pull request (or I missed too?), so please tell me before changing something like this next time.

**Comment by saagarjha** [comment]
It had a small mention in "AutoLayout improvements", but I agree I should have been a bit more clear. I've used aspect constraints because they make it easier to resize objects without losing the aspect ratio (for example, if we think the control bar is too small). If the images are not square, their aspect ratio should be used instead of the 1:1 we have right now, but either way there's fewer magic numbers in the storyboard.
