### ISSUE TITLE
Cannot into full screen mode in Yosemite(10.10.5)

### ISSUE THREAD

**Issue by kjstart** [lhc70000/iina#355]
**System and IINA version:**

- macOS 10.10.5
- IINA 0.0.4

**Expected behavior:**
Able to switch to full screen mode.

**Actual behavior:**
Can not switch to full screen mode.

**Steps to reproduce:**
1. During playback double click mouse or select menu->video->full screen.  Screen size does not change.
2. Click enlarge button on player's title bar, it could enlarge but not full screen.

**How often does this happen?**
Always

**Comment by kjstart** [comment]
Full screen is very important for video playback, please help to fix it. Thanks.

**Comment by kjstart** [comment]
It is worked in build8, which is uploaded by author in another issue about crash. #344
So I assume it is got been fixed.

**Comment by lhc70000** [comment]
Fixed in develop branch and will be available in 0.0.5.

**Comment by shrx** [comment]
Does not work with legacy full screen option enabled in 0.0.15. Should I open a new issue?

**Comment by lhc70000** [comment]
@shrx Please describe your problem precisely, like what do you expect and what actually happened.

**Comment by shrx** [comment]
**System and IINA version:**

- macOS 10.10.5
- IINA 0.0.15 Build 68

**Expected behavior:**
When I enable "legacy full screen", I expect it to work.

**Actual behavior:**
When I double click on the video to enter full screen, or select `Video -> Enter Full Screen` from the Menu bar, nothing happens. Windows stays the same size as before.


**Steps to reproduce:**
1. Enable "legacy full screen".
2. Try to enter full screen when a video file is opened.

**How often does this happen?**
Always. Entering full screen works if I disable "legacy full screen".

**Comment by alejx** [comment]
@shrx Unfortunately we are going to drop OS X 10.10. Please upgrade to a newer version of macOS. If the problem still exists after upgrading your system, please open another issue.
