### ISSUE TITLE
Add an initial interface for better video arrangement, plugin management etc.

### ISSUE THREAD

**Issue by ForeverArt** [lhc70000/iina#370]
**Feature Request:**

- Add an initial interface for better video arrangement where users could easily converged resources, classify videos into virtual folders or even mark as like and add comments for themselves.

- An initial interface also make it convenient to change settings, manage plugins that maybe come out in the future.

In conclusion, i think IINA could have an initial interface for more users' convenience and also for showing IINA.

**Comment by lhc70000** [comment]
You can enable this option as a workaround:
![f4d3e757-4227-4afb-bc8d-442b69d3a94f](https://cloud.githubusercontent.com/assets/8478049/22877005/598c7f3e-f20e-11e6-9d4a-bece8eb268e8.png)

**Comment by euf** [comment]
@ForeverArt I disagree with the necessity of video arrangement tools because IINA’s beauty comes from its simplicity — it looks and acts as light as QuickTime, but offers the power of VLC. Bloating player with own media library, virtual folders, tagging systems et cetera is the wrong way of attracting users.

**Comment by lhc70000** [comment]
We added a welcome window in 0.0.12. Currently there's no plan on other initial windows.
