### ISSUE TITLE
Setting to set self as default for file types

### ISSUE THREAD

**Issue by matthewdias** [lhc70000/iina#375]
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.5

**Expected Behavior:**

When enabled, IINA becomes the default app to open enabled file types, without requiring the Get Info rigmarole.

**Comment by euf** [comment]
It would be also great to set up file associations in preferences, like several other apps do.
http://unarchiver.c3.cx/unarchiver_screenshot1.jpg

**Comment by Nes-si** [comment]
please, at least separate audio/video file types associations. I sure most users want to set IINA as default video player, but not audio.

**Comment by euf** [comment]
The example realization of file associations dialog can be seen in the source code of the app «The Unarchiver», screenshot of which I posted before. 
Here is its repository: https://bitbucket.org/WAHa_06x36/theunarchiver/
I am not good at Objective-C, but corresponding class seems to be `CSFileTypeList`.
Anyone interested in implementing this feature can use the code freely since its under LGPL.

**Comment by kocoman2** [comment]
Where is the option to set iina to play all video files?  Quicktime is still overriding ?

Thx
