### ISSUE TITLE
Proxy setting

### ISSUE THREAD

**Issue by chy9002** [lhc70000/iina#404]
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.5

![](https://ww4.sinaimg.cn/large/006tKfTcgy1fcted5lm6sj30qo0kmgol.jpg)
I'm not sure how to set proxy for youtube-dl in IINA, I try to use `--proxy socks5://127.0.0.1:1080` and `proxy=socks5://127.0.0.1:1080`, but they both don't work.

**Comment by lhc70000** [comment]
According to mpv documentation, you need to [escape](https://mpv.io/manual/master/#escaping-spaces-and-other-special-characters) it.

Examples:
```
proxy=%14%127.0.0.1:8080
```
```
proxy=%21%http://127.0.0.1:8088
```
`socks5://` doesn't work on my computer weirdly.

However, even though you set the proxy for youtube-dl, mpv still can't play the video since it only get parsed link from youtube-dl, rather than video data. Setting environment variable `http_proxy` will work, but there's no entrance for setting environment variables in IINA.

**I'll add support for `http_proxy` in next version.**

**Comment by lhc70000** [comment]
Please use HTTP proxy in 0.0.6 instead of youtube-dl options. It works for both youtube-dl and FFmpeg (playback).

**Comment by chy9002** [comment]
It's worked. Thanks! 👍

**Comment by Justsoos** [comment]
yeah, so, is it a way to pass the proxy settings with command line now?
like:
`$iina 'iina --proxy 127.0.0.1:1080 'https://www.youtube.com/watch\?v\=some_hash'`
and also pass the same proxy setting to youtuble-dl.

and second, iina does not treat well with backslash escape characters from CLI para, the example above will cause error.

**Comment by Justsoos** [comment]
resolved by tests:
1, set pac proxy
![image](https://user-images.githubusercontent.com/3480043/65934437-fd993d00-e447-11e9-8810-d7f1ecd6f786.png)

2, set iina with youtube-dl proxy
![image](https://user-images.githubusercontent.com/3480043/65934454-11dd3a00-e448-11e9-983e-213a5797d8f3.png)

must be HTTP proxy, SOCKS proxy not work!

3, and then you can run in terminal like:
```$iina https://www.youtube.com/watch?v=xxxx```

4, and be careful, iina recent version has bugs of backslash escaping parameters, some terminal app could pass URL like:
```$iina https://www.youtube.com/watch\?v\=xxxx```
it cause error.
so, try to set an alias to use iina, like
```
alias iina='iina'
```

End
