### ISSUE TITLE
Another App copied IINA without permission | 有人直接抄袭了你的代码并拿来售卖

### ISSUE THREAD

**Issue by shule1987** [lhc70000/iina#420]
你好， 有人在mac 的应用商店售卖一款播放器， 界面和你的一样， 毫无疑问是抄袭了你的代码， 我很喜欢你的软件， 但是不齿这种严重的抄袭行为， 下面是这个软件的链接
https://itunes.apple.com/cn/app/niceplayer-hardware-decode-external-subtitle/id1172779350?mt=12

**Comment by ousui** [comment]
真够无耻的……

**Comment by shule1987** [comment]
我来向苹果举报一下

**Comment by banxi1988** [comment]
我看了下项目的开源协议是 GNU, 那按我的理解的话, 打包拿去买, 好像符合 GNU 的使用规则.
但是如果有修改是应该也要开源.

**Comment by zhuol** [comment]
支持这边也出一个发到APP STORE, 有人想一起做么？我可以建一个IINA的APPLE ID.

**Comment by HarukaMa** [comment]
@banxi1988 **不符合**。GPL 和苹果商店的附加授权不兼容。

别忘了 VLC 当年怎么下架的。

**Comment by HarukaMa** [comment]
@zhuol 不用单独为了这个再交 648 了……

**Comment by shule1987** [comment]
使用了开源代码也应该是把所修改的代码贡献出来的， 这个抄袭者应该没有把代码贡献出来，而且根本没提到你

**Comment by HarukaMa** [comment]
@shule1987 其实光 GPL 一点就有足够理由让他下架了。

**Comment by shule1987** [comment]
好啊， 我之前一直想找一个人合作一下mac版的视频播放器， 我是deepin的设计总监，设计是我最擅长了

**Comment by zhuol** [comment]
@HarukaMa, 我觉得这个项目很好，最近正在看代码也正在用，我希望可以有更多的人用到，所以花点钱也没什么。如果原作者不介意的话，我们可以把它弄成免费版的发在APP STORE，应该会有更多的人喜欢的.

**Comment by HarukaMa** [comment]
@zhuol 实际上是创始人已经专门买过了开发者账号了……从 0.0.5 开始应用都已经是签名过的了。

**Comment by zhuol** [comment]
@HarukaMa 哦哦哦，这样子啊，那就挺好的了~

**Comment by HarukaMa** [comment]
@zhuol 等以后基本稳定了应该是会免费放 MAS 的……

**Comment by zhuol** [comment]
@HarukaMa, 好，支持支持~

**Comment by lhc70000** [comment]
感谢指出，已向苹果反馈。

**Comment by saagarjha** [comment]
What this developer has done is almost certainly against the GPL, since they have provided neither a copy of the source code nor the license. In addition to reporting this to Apple, you should also probably reach out to the developer. Their [support site](http://www.lovewhatyoudo.cn) has an email address that you might be able to contact them with.

@lhc70000 We'll have to have a discussion if you're planning to put IINA on the App Store, since it links to the private PIP.framework, which would be grounds for rejection during review (although, if this app got on, who knows how thorough the review is 😄). We might have to create a separate copy of IINA that doesn't have Picture in Picture functionality if we do plan to go that route.

**Comment by HarukaMa** [comment]
@saagarjha I think that since he has already put up that app to MAS, there would be no point contacting him as he won't stop doing that (almost certainly). Unless you are going to threaten him with a lawyer's letter.

As for the store review, a try with private framework won't hurt too much?

**Comment by lhc70000** [comment]
@saagarjha Thank you for noticing this issue - as the conversation was in Chinese.

Lots of users did requested for a MAS version although I personally don't like it. It's still under consideration mainly for sandbox restrictions, mpv's license etc, and I don't have so much time recently. We definitely need to have another MAS version if we decided to do this.

**Comment by saagarjha** [comment]
Google Translate goes a long way :)

**Comment by shule1987** [comment]
很高兴终于被苹果下架了

**Comment by shule1987** [comment]
又发现了另外一个抄袭的，我擦
https://itunes.apple.com/cn/app/tangbo-video-player/id1196326728?mt=12

**Comment by saagarjha** [comment]
Sigh…although, it does appear that the author actually put some effort into this one. There's a bunch of new icons in the Settings panel and a share feature.

**Comment by alejxd1950** [comment]
@shule1987 https://itunes.apple.com/us/app/tangbo-video-player/id1196326728?mt=12 alway on App Store.

**Comment by shule1987** [comment]
@alejx that's another illegal copy

**Comment by goodman-capu** [comment]
How to report illegal apps to Apple? Can we do something to help?
歪个楼 这个标题好像张全蛋的语气 hhh

**Comment by lhc70000** [comment]
@goodman-capu 
https://www.apple.com/legal/internet-services/itunes/appstorenotices/, but this link is only for "copyright owners".

@saagarjha 
Any project based on IINA shouldn't appear in AppStore since it violates GPL. We need to distribute IINA in another license even if we are going to make a MAS version by ourselves. (BTW The icons look terrible to me.)

**Comment by sn0wyfall** [comment]
This is unacceptable. The develop is selling the app on the App Store? Not only that, but for a "discount" of $8. How low can you get?

**Comment by Hanchor** [comment]
Furious about this issue. Is there any way we could report these developers to Apple so Apple could ban those developer accounts? or could we ask for a lawyer sending out a cease and desist letter to developers who illegally used IINA's original code? I'm now studying in Law school, sadly not IP related area, but please let me know if I could offer any help. I could reach some IP lawyers to see if they want to accept this as their pro bono work (I hope I could find someone).

**Comment by lhc70000** [comment]
This is what Apple replied:

> However, it appears that you are not the legal rights holder to the application(s) referenced in your submission.  We cannot act until we receive such notice from the legal rights holder that their rights are being infringed.  Please refer to our DMCA page <http://www.apple.com/legal/trademark/claimsofcopyright.html> for further information on how a legal rights holder may file a complete and valid notice of infringement.

> If you are a legal rights holder and would like to resubmit your claim,  please visit the following link: 
> 
> http://www.apple.com/legal/itunes/appstorenotices/
> 
> Additionally, please provide us with the following information:
> 
> • a representation, under penalty of perjury, that you are or that you represent the authorized rights holder of the rights infringed by the app.
> • the name or company name of the rights holder whether yourself or the party being represented by you.
> • a description of the rights infringed, and by which aspect of the app.
> 

Seems that they need me to prove I'm the legal rights holder. I'm busy with coursework these days and didn't even read the DMCA page, but in fact I have no idea how to prove that, although I think violating GPL is an enough reason.

It's possible to submit content dispute form here http://www.apple.com/legal/internet-services/itunes/appstorenotices/#/contacts?lang=en, but it's only for right owner.

**Comment by Hanchor** [comment]
I'll try to do some basic legal research and try to write a memo to let you know about the basic knowledge about the copyright of OSS program.... But just don't count on me right now since you could imagine how much work we have in law school. I'll try my best, and I'll consult some people I known about this issue.
Hope we could find a proper solution.

**Comment by HarukaMa** [comment]
Any sign or record that Chinese courts would respect OSS licenses? IINA didn't apply for anything in mainland china (e.g. 软著) or smth like that.

Yes as a Chinese I don't trust our own court system in some areas.

**Comment by Hanchor** [comment]
I'm not very sure... My limited Chinese bar IP knowledge did not cover anything like OSS licenses. I have to do some researches first. But since the so-called infringing software is also provided in U.S. App Store. Perhaps we could allege the jurisdiction in U.S. (or at least for U.S. App store.) For this issue, I have to check the agreement provided by GitHub and the GPL... this would be a huge task....

**Comment by lhc70000** [comment]
@Hanchor I think the goal is just to convince Apple, a U.S. company, to remove infringing Apps from Mac AppStore, which should not have much thing to do with Chinese law. BTW, thanks for your effort.

**Comment by Hanchor** [comment]
@lhc70000 That's what I'm considering about. being in U.S. law school might provide me some help~ I'll have a try.

**Comment by sn0wyfall** [comment]
@Hanchor I agree, thanks for trying to help out

**Comment by Hanchor** [comment]
@lhc70000 I've sent you an email. Probably I wrote it way too complex. 

The basic info. is that the Apple App Store Policy is not compliance with GPL. if the software goes to App Store, it automatically broke GPL. so we should treat the software a breath of GPL.

In the email I sent to you, you could find a link (in the very last of my email). Someone provide an alternative method to solve this problem, which should be easier for you since the IINA group is getting bigger which means the number of copyright owners is getting bigger.

Or we could simply fill a report to FSF since it's a violation of GPL, and ask for their help.

I only know basic knowledge about coding, so please check the alleged infringing software is actually using the original code of IINA before you take steps.

Please let me know if I could do anything more. Sorry for unorganized email, I finished it so hurriedly.

**Comment by jqqqqqqqqqq** [comment]
https://itunes.apple.com/cn/app/pilipala/id1322234917?l=en&mt=12

**Comment by saagarjha** [comment]
Yes, we're aware of this one as well. We're working on it!

**Comment by sn0wyfall** [comment]
It's really not nice seeing other 'developers' ripping off IINA's tremendous work!

**Comment by Co2333** [comment]
I'd like this player to be put on App Store with the official one even if it is paid.
