### ISSUE TITLE
Auto-load subtitles in  customized folders

### ISSUE THREAD

**Issue by AlexaraWu** [lhc70000/iina#432]
Auto-load subtitles in  customized folders such as:
`./Subtitles`
`./Subs`
or so on.

**Comment by euf** [comment]
Should the folders be really customizable? Maybe just add an option to look for subtitles in all subfolders? 
It should be easier to implement running through all subfolders than adding a custom dialogue, and it will be fast, since people don’t usually have complicate folder structure for movies. 
The option could look like this:
![2017-05-29 3 14 56](https://cloud.githubusercontent.com/assets/11754264/26533190/bc2c1904-441d-11e7-9c6d-c4a38cce9cff.png)

**Comment by alejx** [comment]
![screen shot 2017-05-29 at 11 15 20 am](https://cloud.githubusercontent.com/assets/20237141/26535771/f133ad48-4462-11e7-87cb-f3e561006d0f.png)

This is the new subtitle auto load looks like. You can add your customized folders in the last box.
Fixed in develop. See #673 .
