### ISSUE TITLE
Add scriptability

### ISSUE THREAD

**Issue by shengdie** [lhc70000/iina#547]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.7

**Expected behavior:**
I am trying to write a desktop lyrics extension for iina, but I found it is not scriptable, so I hope you could consider making it scriptable. it would be helpful for writing extensions.

**Comment by inflation** [comment]
If you have expierence with MPV scripting, it's not hard to get what you want through Lua. And you can turn on MPV config in `Prefrence > Advance`

**Comment by lhc70000** [comment]
Please refer to https://mpv.io/manual/stable/#lua-scripting.

**Comment by shengdie** [comment]
OK, I will have a look. Thanks.

**Comment by padi** [comment]
I've read the mpv docs on lua scripting and I've used mpv in the past. Is it enough to enable "Use config directory: "? 

![Screenshot_5_6_19__6_14_PM](https://user-images.githubusercontent.com/807110/58949115-443e9980-87be-11e9-9c2a-73e97f6625fe.png)

I've installed an mpv script in ~/.config/mpv/scripts/autosub.lua (https://github.com/vayan/autosub-mpv) and I can't seem to activate it. I've also tried "script=<path-to-file>" option and it doesn't seem to activate in the way i use it in mpv.

**Comment by lhc70000** [comment]
This is because the key binding registered through lua is not recognized in IINA.

Please refer to #1053 on how to add the key binding manually (the action for this script should be something like `autosub/auto_load_subs`). However since this script also uses mpv's OSD which is disabled by default in IINA, you won't see the messages displayed by this script even if it functions normally.

A plugin system based on JavaScript is working in progress and will be available in IINA 1.1, which should be a better way to extend IINA's functionality. Please stay tuned.
