### ISSUE TITLE
Switching OSCPosition doesn't work properly.

### ISSUE THREAD

**Issue by matsune** [lhc70000/iina#613]
Preferences > UI > Layout

**Expected behavior:**
OSCPosition should be switched to selected layout.

**Actual behavior:**
Switched to previous selected layout.

https://github.com/lhc70000/iina/blob/develop/iina/MainWindowController.swift#L602
I think
```swift
switch newPosition {
```
or `oscPosition = newPosition` should be called before this switch.

If anyone isn't touching here, can I make PR?

**Comment by lhc70000** [comment]
You're right. Although it actually works well: due to strange logic of user defaults, `setupOnScreenController(position:)` is called twice each time, so at the second time `oscPosition` becomes correct. I suggest:

- Check whether the value really changed in the listener ([L602](https://github.com/lhc70000/iina/blob/develop/iina/MainWindowController.swift#L602))
- Call `oscPosition = newPosition` earlier.

0.0.8 is going to be released today, so it's better to finish it before tonight XD

**Comment by matsune** [comment]
In my environment, `setupOnScreenController(position:_)` is not called twice.
I changed value and observed `setupOnScreenController(position:_)`  by using Breakpoint, this method is called once. And`newPosition` was correct changed value.

**Comment by lhc70000** [comment]
Then please submit a PR.
