### ISSUE TITLE
Subtitle preference window too small

### ISSUE THREAD

**Issue by tehabe** [lhc70000/iina#619]
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.8

**Expected behavior:**
All settings of the subtitles preferences should be visible.

**Actual behavior:**
They are not. See the screenshot.

![iina subtitle preferences](https://cloud.githubusercontent.com/assets/19303903/25705170/aa1eccd8-30dc-11e7-9f92-03bb19f0f1d4.png)

**How often does this happen?**
Everytime

**Comment by lhc70000** [comment]
It's designed to be scrollable or the window height will be larger than MacBook Air 11's screen.

I'll try to find a better way to solve this problem.

**Comment by megadr01d** [comment]
Suggestions...

- Smaller font size

![Smaller font size](https://www.maketecheasier.com/assets/uploads/2009/05/movist-subtitle-preferences.jpg)

- Tabs

![Tabs](http://a2.mzstatic.com/us/r30/Purple/v4/82/eb/a9/82eba92f-b7b3-c352-d5d8-923d1d49d301/screen1280x800.jpeg)

- Wider window (instead of taller)...

![Wider window](https://trac.videolan.org/vlc/raw-attachment/ticket/13674/Captura%20de%20pantalla%202015-01-20%20a%20las%2010.19.14.png)

...with elements side by side

![Elements side by side](http://cdn.makeuseof.com/wp-content/uploads/2010/04/03c-Full-Screen-Navigation-Preferences.jpg)

**Comment by Nes-si** [comment]
@lhc70000 I understand that you've set smaller height for Air 11''. But the reduced height produces a vertical scroll bar. Then the vertical scroll occupies some width and produces a horizontal scroll. 
![preference 2017-05-13 01-40-58](https://cloud.githubusercontent.com/assets/5188972/26019496/4fe7aaac-377e-11e7-8401-f1422386c986.png)
So please, at least, set proper width to eliminate a horizontal scroll appearing.

**Comment by lorenzofanchi** [comment]
The tabs option in megadr01d's example looks very elegant, I think..

**Comment by lhc70000** [comment]
Fixed/added in 0.0.13.
