### ISSUE TITLE
Disabling OSD

### ISSUE THREAD

**Issue by MingChenLee** [lhc70000/iina#641]
![2017-05-11 14 18 12](https://cloud.githubusercontent.com/assets/26946802/25935762/3d9fa174-3657-11e7-96ed-8e2556f4e2c2.jpg)
< In the latest version, I found this feature in the upper left corner of the video playback window. Looks like the whole page is not very coordinated. Hope that you can remove it. Or to provide a choice for the user to choose to close or open.>

**Comment by lhc70000** [comment]
@MingChenLee Do you mean the OSD (on screen display) or the progress bar in it?

**Comment by MingChenLee** [comment]
Yes, that's what you see the little progress bar, you call it OSD?

**Comment by megadr01d** [comment]
>  you call it OSD?

[On-screen display](https://en.wikipedia.org/wiki/On-screen_display)

> Looks like the whole page is not very coordinated.

I'm curious, what do you mean by "not very coordinated"? I personally like it and hope it's not removed but an option to hide OSD messages would be OK.

**Comment by MingChenLee** [comment]
I would like to ask you in the next version, add an option to hide the OSD.On is not very coordinated. The reason is that the OSD display is a black piece.

**Comment by saagarjha** [comment]
Do you have an issue with the OSD whenever it appears, or just when the video is paused?

**Comment by edrozenberg** [comment]
Another vote to be able to permanently hide/remove top left progress box/OSD.

Many of us appreciate IINA because it's a lot more similar to QuickTime Player than VLC ever was. As such, getting rid of extraneous elements such as the OSD is another step in the right direction.

The final step would be for QuickTime Player to support all common video formats so there's no more need for additional video players. Until that day comes (looks like never), thanks IINA and VLC for playing formats Apple doesn't want to.

**Comment by ElhemEnohpi** [comment]
Fyi, there is a work-around for this. Check the box "Use mpv's OSD" in Preferences/Advanced. Create an "additional mpv option" with name `osd-level` and value `0`.
