### ISSUE TITLE
Version number not updated.

### ISSUE THREAD

**Issue by kkanungo17** [lhc70000/iina#645]
The 0.0.9 release still shows version number as 0.0.8. This causes redundant update messages on starting IINA.

**Comment by KizzyCode** [comment]
Are you sure that you have deleted all old versions of IINA? Sometimes macOS tends to run an old version from somewhere – I had the same issue (I had an old version still laying in brew-cask's cache)...
You can try 'find / -name "IINA.app" 2>/dev/null' in Terminal to locate all elements named IINA.app.

**Comment by kkanungo17** [comment]
Yeah, for some weird reason copying over the newer version didn't replace the older version in /Applications. Deleting and moving again fixed it.

**Comment by megadr01d** [comment]
By the way, does anyone know why the version is not showing when you call Quick Look on IINA? It just shows the `NSHumanReadableCopyright` key but not the `CFBundleShortVersionString` key containing the version, although it shows both in the **Get Info** window.

It's strange because DiskWarrior's `Info.plist` also contains both keys and they show up correctly when invoking Quick Look.

**Comment by kkanungo17** [comment]
The build number is not updated in the Info.plist file in the develop branch. I'll open a pull request to fix this.

**Comment by lhc70000** [comment]
Closing this issue.

@megadr01d You can open another issue about that.

**Comment by megadr01d** [comment]
@lhc70000 [OK](https://github.com/lhc70000/iina/issues/698).
