### ISSUE TITLE
smb support

### ISSUE THREAD

**Issue by dumo** [lhc70000/iina#734]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**

Please support SMB share, when I use the SMB share, iina not fluency.

**Comment by chenyiping1995** [comment]
Technically I have tried playing media resources over SMB so I personally do not think it is a bug of IINA.

Do you have enough bandwidth to play the media resource on your SMB share? Try using 5G Wi-Fi and come closer to the wireless router MAY help solve the problem.

Also does your computer provide necessary speed? I mean if you are trying to play 4K 60FPS HEVC then maybe it has to do with the performance of your computer.

**Comment by Miigon** [comment]
I think the user experience will be improved if IINA can regard SMB and FTP files as `NetworkResource` and enable buffering HUD for them.

**Comment by chenyiping1995** [comment]
@Miigon 一平 陈:
Due to the limitations of macOS, there is no way for IINA to know that you are playing a file from a SMB share, because it would be mounted under /Volumes (for example, /Volumes/RT-68U/Movies/Sample.mp4). IINA cannot tell whether you are playing a media resource from such location, thus there would be no buffer bar available.

You can try playing your media resource on your SMB share using ANY other player, including the built-in QuickTime Player, and no one will handle the buffer bar.

**Comment by Miigon** [comment]
@chenyiping1995 I see.But having a shortcut to turn on buffering HUD is also good.

**Comment by Rainsho** [comment]
Actually when I played a resources through SMB or FTP, the player didn't do well with it. It will paused every 3-5 minutes especially when I use the forward and backward function. I don't know it caused by the network reason or other reasons, but when I use other player like Movist played the same resources it had never happened.

**Comment by Rainsho** [comment]
I changed the RTSP model to UDP, it had performanced more fluency than before.

**Comment by jackr-m** [comment]
For other people arriving here from Google, I found that IINA and MPV were not able to reach the full network speed on my SMB share that could be achieved with other apps. Following [this comment](https://github.com/mpv-player/mpv/issues/14670#issuecomment-2289607390) from https://github.com/mpv-player/mpv/issues/14670 and adding `--stream-buffer-size=5MiB` to MPV fixed the issue (allowing the network speeds I was expecting). Adding this as an "Additional mpv option" in IINA also worked.
