### ISSUE TITLE
Options for default screen display size

### ISSUE THREAD

**Issue by snowshoes** [lhc70000/iina#760]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**
**THIS IS A QUESTION, NOT AN ISSUE**

Hey there, I'd like to know if there are options to set default screen display size while launching the application, I've checked the options in setting but to no avail

Please tell me know whether if it's available or not, thanks in advance

Best Regards

**Actual behavior:**
No setting options for default screen display size

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by snowshoes** [comment]
Hey there, thanks for adding the question label ;)
In fact, IINA opened up a video in its original size, no matter of its type.

**Comment by lhc70000** [comment]
IINA supports mpv's `geometry` option: https://mpv.io/manual/stable/#options-geometry

You can set it in `Preference > Advanced`.

**Comment by snowshoes** [comment]
Thanks @lhc70000 , it works like a charm !

**Comment by JohnClay** [comment]
@lhc70000 Unfortunately, this doesn't work on multiple monitors. The coordinates only seem to be respected for the primary display; secondary monitors can't reliably be used.

Any chance of getting support for mpv's 'screen' setting? I would much prefer having all videos open on a secondary monitor, rather than the primary.
