### ISSUE TITLE
What is the auto seek type?

### ISSUE THREAD

**Issue by nhooyr** [lhc70000/iina#785]
Could not find documentation on this anywhere. What precisely does it do?

Is the difference between the keyframe and exact seek types that exact uses an acceleration curve?

**Comment by lhc70000** [comment]
I'll try to explain this briefly. Let's say you have a video with 20 frames. Among them 1, 6, 11 and 16 are **key frames**.

```
[1] 2 3 4 5 [6] 7 8 9 10 [11] 12 13 14 15 [16] 17 18 19 20
```

**key frames** can be decoded independently, so if you are seeking to frame 11, the player only needs to decode frame 11.

**other frames** _cannot_ be decoded independently, so if you are seeking to frame 14, the player needs to decode frame 11, 12, 13 and 14, which is obviously much slower.

**key frame seek** will only seek to key frames. If you are seeking to frame 14, it will seek to frame 11 instead. It's faster but not accurate. This is the default option for almost all players.

**exact seek** will seek to the exact frame you requested. It's slower, but accurate. For "small" videos that don't need much time to decode a frame, it provides better user experience; but for large videos, it may cause horrible lags and extremely high CPU usage.

The reason why exact seek seems to "use an acceleration curve" is illustrated below. When you scroll horizontally, IINA tries to seek to frame according to scroll events, which _always_ includes elasticity, but due too keyframe seek, you can't perceive the elasticity:

```
Requested: 11 12 13 14 15 16 17 18 19
Keyframe:  11 11 11 11 11 16 16 16 16 
Exact:     11 12 13 14 15 16 17 18 19
```

QuickTime definitely optimized these stuff and made seeking accurate and smooth, but considering the limited formats it supports, the same trick may be difficult to apply on general media players like mpv.

"Auto seek" in IINA tries to check whether it's a "small" or "large" video (by recording the time needed for the first seek) and choose the seek type for it. It's my effort to make seeking more user-friendly, but since its behavior is rather strange (user experience are totally different for two types), I'm not going to recommend or document it.

**Comment by nhooyr** [comment]
I understand now, thank you!
