### ISSUE TITLE
Open multiple videos

### ISSUE THREAD

**Issue by jhaberstro** [lhc70000/iina#79]
An advantage that Quicktime Player.app has over IINA and VLC is that it can open multiple videos at the same time. Having this feature in IINA would likely make it my go to video player.

**Comment by marlowe310** [comment]
I'd like to add my voice to this feature request -- would happily jump off Movist for iina if it could support multiple windows!

**Comment by MacCamintosh** [comment]
I'm also adding my voice to this feature request.
To to that now, I'm using a custom Apple Script, modified from "open with MPV.app" but I'm getting some weird errors from MPV api, and it make the player to forget where the video was stoped. But since this is third-party, and does not occur with IINA used normally, there's no need to provide a bug report. (expect if wanted?)

I'll be very happy to see this feature natively in IINA.

**Comment by saagarjha** [comment]
It's probably not supported, but we could still take a look at that AppleScript :)

**Comment by MacCamintosh** [comment]
That would be cool @saagarjha!

You can take at look at [the original Apple Script](https://github.com/basakil/OpenWithMPV.app).
(I just had to change "/Applications/MPV.app" to "/Applications/IINA.app")

But if you want to be packed in an .app [so here it is!](https://monosnap.com/file/g4CfgjvY83F8MJ0fKL9YkT5LvlbDZ3)

**Comment by saagarjha** [comment]
Works fine for me…

![](https://cloud.githubusercontent.com/assets/13786931/24261164/53d076be-0fb3-11e7-9c3a-c39b6c187c07.png)

**Comment by MacCamintosh** [comment]
This happen sometimes, not always. :(
It may happen at the first try, or not... I tried severals to "hard"-test it, and it varies very much. It's often every 4~6 files, but I just got one that took 17 try to get that error.
Here are the errors I always got: (Two dialogue box) 

- **Error** Error error setting option (-7) when setting user option sub-back-color.

- **Error** Fatal error: MPV API error: "error setting option", Return value: -7. The application will exit now.

Since I suppose "sub-back-color" is referring to subtitles, tried to disable subtitles auto-load and ignore ASS style: Didn't work :(

**Comment by lhc70000** [comment]
@MacCamintosh This problem exists from the initial version. I think it's a bug of mpv's API.

**Comment by MacCamintosh** [comment]
@lhc70000 oh, okay!
I'm using IINA since ~v0.0.2 Build 3 and never get that bug (luck, I guess) until I use this AppleScript. So, I thought it was the AppleScript.

**Comment by injust** [comment]
Related issue: https://github.com/iina/iina/issues/3531

IINA doesn't exactly have parity with QuickTime Player for opening multiple videos. For example, `open *.mp4` will play one video and add the rest to the playlist, instead of actually opening multiple videos.
