### ISSUE TITLE
iOS screen recording looks over saturated

### ISSUE THREAD

**Issue by xhacker** [lhc70000/iina#939]
**System and IINA version:**

- macOS 10.13
- IINA 0.0.12 Build 37

**Steps:**
Open attached video in IINA and QuickTime Player. Video in IINA looks over saturated. See screenshots. If you take a screenshot using IINA, the saturation is correct.

Screenshot by IINA:
![screenrecording_08-03-2017 22 09-0001](https://user-images.githubusercontent.com/1051813/28925836-9a08ec08-7898-11e7-83f7-89a9c7292200.png)

System screenshot while IINA is playing:
<img width="606" alt="2017-08-03 10 10 40" src="https://user-images.githubusercontent.com/1051813/28925839-9d026e98-7898-11e7-8bc1-bee3ede2ad37.png">
[ScreenRecording_08-03-2017 22:09.MP4.zip](https://github.com/lhc70000/iina/files/1197434/ScreenRecording_08-03-2017.22.09.MP4.zip)

**How often does this happen?**
Always.

**Comment by tellowkrinkle** [comment]
Looks like the issue is with playback of videos with the `yuvj420p` pixel format.  You can recreate the issue with a video generated by this command: `ffmpeg -f lavfi -i color=white:640x480:d=3 -pix_fmt yuvj420p output.mp4`

The issue is also reproducible with `mpv`.  Have you submitted a bug report there?

**Comment by tellowkrinkle** [comment]
Oh btw, I couldn't find one so I've filed an issue with mpv: https://github.com/mpv-player/mpv/issues/4946
